---
- name: Test dynamic inventory for docker
  hosts: all
  become: yes

  tasks:
  - name: Ping docker containers
    ping:

  - name: install nginx latest
    apt:
      name: nginx
      state: latest
      update_cache: yes

#  - name: Installs nginx web server
#    apt: pkg=nginx state=installed update_cache=yes

  - name: Show disk size
    shell: df -h
