# -*- mode: ruby -*-
# vi: set ft=ruby :

PRIVATE_NET="192.168.56.24"
PUBLIC_NET="192.168.88."
#DOMAIN=".example.com"
DOMAIN=""

vm_arr=[
  {
    :hostname => "vm1" + DOMAIN,
    :ip_public => PUBLIC_NET + "51",
    :ip_private => PRIVATE_NET + "1",
    :ram => 1024,
    :synced_folder => false,
    :provision_shell_path => "install.sh"
  },
  {
    :hostname => "vm2" + DOMAIN,
    :ip_public => PUBLIC_NET + "52",
    :ip_private => PRIVATE_NET + "2",
    :ram => 1024,
    :synced_folder => true
  },
  {
    :hostname => "vm3" + DOMAIN,
    :ip_public => PUBLIC_NET + "53",
    :ip_private => PRIVATE_NET + "3",
    :ram => 4096,
    :synced_folder => true
  }
]

Vagrant.configure("2") do |config|
  vm_arr.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = "hashicorp/bionic64"
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip_private]
      node.vm.network "public_network", ip: machine[:ip_public]
      node.vm.synced_folder "./", "/home/vagrant/workdir", disabled: machine[:synced_folder]
      node.vm.provider "virtualbox" do |vbox|
        vbox.customize ["modifyvm", :id,
          "--memory", machine[:ram],
          "--nictype1", "virtio",
          "--nictype2", "virtio",
          "--name", machine[:hostname]]
      end
      if (!machine[:provision_shell_path].nil?)
        node.vm.provision "shell", path:  machine[:provision_shell_path] , privileged: false
      end
    end
  end
end
